function motorspinup3V1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MOTORSPINUP3V1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  MOTORSPINUP3V1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  motorspinup3V1 = importfile("/Users/evan/Documents/Arduino/feedback_project/motor_spin_up_3V.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Apr-2023 11:26:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestampms", "Angle", "Pulses", "Speed", "VarName5"];
opts.VariableTypes = ["string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["timestampms", "Angle", "Pulses", "Speed", "VarName5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["timestampms", "Angle", "Pulses", "Speed", "VarName5"], "EmptyFieldRule", "auto");

% Import the data
motorspinup3V1 = readmatrix(filename, opts);

end